#!/bin/sh
MODEM_INTF=$1
[ -z "$MODEM_INTF" ] && return
SIGNAL_INFO=$(timeout 8 gcom sig -d $MODEM_INTF)
[ -z "$SIGNAL_INFO" ] && return
RSSI=$(echo $SIGNAL_INFO | grep 'Signal Quality' | awk -F: '{print $2}' | awk -F, '{print $1}')
[ -z "$RSSI" ] && return
PERCENT=$(((RSSI * 100) / 31 ))
([ $PERCENT -gt 100 ] || [ $PERCENT -lt 0 ]) && PERCENT=0
echo $PERCENT
